package events.order;

public enum OrderEventType {
    VALIDATE_ORDER,
    VALIDATION_PASSED,
    VALIDATION_FAILED,
    ALLOCATE_INVENTORY,
    ALLOCATION_SUCCESS,
    ALLOCATION_FAILED,
    ALLOCATION_NO_INVENTORY,
    INCREASE_INVENTORY,
    PICKUP_ORDER,
    DELIVER_ORDER,
    DELIVERY_SUCCESS,
    DELIVERY_FAILED,
}
